import './style.css';

document.querySelector<HTMLDivElement>('#app')!.innerHTML = `
  <header class="site-header"><a class="brand" href="/" aria-label="Replay Partner ホーム"><span class="brand-symbol">⟲</span> REPLAY <span>PARTNER</span></a><nav aria-label="サイト内"><a href="#concept">作品について</a><a href="#how">遊び方</a><a href="#design">設計</a><a class="nav-play" href="/game.html">ゲームを遊ぶ ↗</a></nav></header>
  <main>
    <section class="hero"><div class="hero-copy"><p class="eyebrow">BROWSER PUZZLE · 10 STAGES</p><h1>昨日の自分と、<br><em>扉を開こう。</em></h1><p class="lead">行動を記録し、過去の自分を再生する。分身と役割を分けて進む、固定画面の2Dパズル。</p><div class="hero-actions"><a class="button primary" href="/game.html">ゲームを遊ぶ <span aria-hidden="true">↗</span></a><a class="button ghost" href="#how">遊び方を見る ↓</a></div><p class="micro">PCのキーボード推奨 · 無料 · アカウント不要</p></div><div class="hero-art" aria-hidden="true"><div class="orbit orbit-a"></div><div class="orbit orbit-b"></div><div class="mock-grid"><span class="mock-player">01</span><span class="mock-ghost">02</span><span class="mock-door">A</span><span class="mock-gate">A</span></div><div class="art-label">RECORD → REWIND → REPLAY</div></div></section>
    <div class="stats-strip" aria-label="作品の特徴"><span><strong>10</strong> ステージ</span><span><strong>2</strong> 体まで分身</span><span><strong>0</strong> 通信・課金</span></div>
    <section id="concept" class="section"><div class="section-intro"><p class="eyebrow">01 / CONCEPT</p><h2>過去の行動が、<br>今の選択肢になる。</h2></div><div class="section-body"><p>記録した行動は、巻き戻した部屋の中で分身として再生されます。分身がスイッチを踏む間に、今の自分が扉を通る。ひとりではできないことを、時間差の協力で解きます。</p><p>反射神経ではなく、順番と役割分担が鍵です。静かな実験施設で、試して、失敗して、もう一度考えられます。</p></div></section>
    <section id="how" class="section dark-panel"><div class="section-intro"><p class="eyebrow">02 / HOW TO PLAY</p><h2>記録して、<br>再生して、進む。</h2></div><div class="step-grid"><article><span class="step-no">01</span><h3>記録</h3><p>Eキーで記録開始。スイッチへ移動し、必要なら待機します。</p></article><article><span class="step-no">02</span><h3>巻き戻す</h3><p>もう一度Eキー。部屋と箱が最初の状態に戻り、分身が再生されます。</p></article><article><span class="step-no">03</span><h3>協力</h3><p>分身が仕掛けを支える間、現在の自分が出口を目指します。</p></article></div><p class="controls-line"><kbd>WASD</kbd> 移動 <kbd>E</kbd> 記録 / 確定 <kbd>Space</kbd> 待機 <kbd>R</kbd> リトライ</p></section>
    <section id="design" class="section"><div class="section-intro"><p class="eyebrow">03 / DESIGN & ENGINEERING</p><h2>遊びやすさを、<br>仕組みから考える。</h2></div><div class="feature-grid"><article><span class="feature-icon">⌁</span><h3>同じルールで再生</h3><p>記録は座標ではなく行動。分身も現在の自分も、同じ衝突判定を通ります。</p></article><article><span class="feature-icon">◇</span><h3>色だけに頼らない表示</h3><p>人物には番号、スイッチと扉には共通の文字を付け、関係を読み取れます。</p></article><article><span class="feature-icon">↶</span><h3>試し直しやすい</h3><p>リトライ、分身の削除、段階的なヒントを用意しました。</p></article></div></section>
    <section class="section screenshot-section"><div><p class="eyebrow">04 / IN GAME</p><h2>施設の中へ。</h2><p>ゲーム画面から取得した画像です。盤面と状態表示を一画面で確認できます。</p><a class="text-link" href="/game.html">プレイ画面を開く ↗</a></div><figure><img src="/screenshots/game-stage-2.png" alt="ステージ2の実際のゲーム画面。分身、スイッチ、扉、操作パネルが見える" loading="lazy"><figcaption>ステージ2「片方の手」の画面</figcaption><details class="demo-details"><summary>実際のプレイ動画を見る（約59秒・無音）</summary><video controls preload="none" poster="/screenshots/game-stage-2.png" aria-label="ステージ1から4までの実プレイ動画"><source src="/videos/demo.webm" type="video/webm">動画を再生できない場合は<a href="/videos/demo.webm">動画ファイルを開く</a>。</video></details></figure></section>
    <section class="section about"><div><p class="eyebrow">05 / ABOUT</p><h2>制作について</h2></div><div><p>田中 優輝 / Yuki Tanaka の就職活動向け作品です。人の理解を助けるUIと、動作を検証できる実装をテーマにしています。</p><p>TypeScript・Phaser 3・Viteを使用。制作時にはAIを設計、実装、文章、検証の支援に利用しています。本人の担当範囲や習熟度は、確認のない断定をしていません。</p><p class="micro">現時点で外部公開URLとGitHubリンクは未設定です。コードと検証資料は成果物に同梱しています。</p></div></section>
    <section class="final-cta"><p class="eyebrow">READY TO REPLAY?</p><h2>もう一人の自分に、<br>会いに行こう。</h2><a class="button primary" href="/game.html">ゲームを始める ↗</a></section>
  </main><footer class="site-footer"><span>© 2026 Replay Partner</span><span>Yuki Tanaka · Browser puzzle project</span><a href="#app">ページ上部へ ↑</a></footer>`;
